// @devchain/shared - Shared types and utilities for Devchain services

// Host utilities
export { HostResolver } from './host-resolver.js';

// Schemas
export {
  CLAUDE_LAUNCH_SETTINGS_MAX_BYTES,
  DEFAULT_CLAUDE_LAUNCH_SETTINGS_JSON,
  validateClaudeLaunchSettingsJson,
  type ClaudeLaunchSettingsValidationResult,
  EnvVarsSchema,
  ExportSchema,
  type ExportData,
  type ExportDataInput,
  ManifestSchema,
  type ManifestData,
} from './schemas/index.js';

// Tunnel wire protocol (shared by local-app + devchain-bridge)
export {
  type TunnelProtocolVersion,
  type TunnelPushFrame,
  type TunnelPushEnvelope,
  TUNNEL_PROTOCOL_VERSION_PUSH,
  SUPPORTED_TUNNEL_PROTOCOL_VERSIONS,
  TUNNEL_PUSH_FRAME_TYPE,
  TUNNEL_PUSH_FRAME_VERSION,
  isSupportedTunnelProtocolVersion,
  isPushCapableTunnelProtocolVersion,
  isTunnelPushFrame,
  type MobilePushTopicRule,
  MOBILE_PUSH_TOPIC_ID_SEGMENT,
  MOBILE_PUSH_TOPIC_ALLOWLIST,
  isAllowlistedTunnelPushTopic,
  type TunnelControlOp,
  type TunnelControlFrame,
  type TunnelLivenessQueryFrame,
  type TunnelLivenessResultFrame,
  type TunnelWorkspaceModeOperation,
  type TunnelWorkspaceModeCommandFrame,
  type TunnelWorkspaceModeResultFrame,
  TUNNEL_CONTROL_FRAME_TYPE,
  TUNNEL_CONTROL_FRAME_VERSION,
  isTunnelControlFrame,
  isTunnelLivenessQueryFrame,
  isTunnelLivenessResultFrame,
  isTunnelWorkspaceModeCommandFrame,
  isTunnelWorkspaceModeResultFrame,
  type ViewportCursor,
  type ViewportScreen,
  type ViewportChangedLine,
  type ViewportFullBody,
  type ViewportDiffBody,
  type ViewportEncryptedFullBody,
  type ViewportBody,
  type TunnelViewportFrame,
  type MobileViewportSseEvent,
  TUNNEL_VIEWPORT_FRAME_TYPE,
  TUNNEL_VIEWPORT_FRAME_VERSION,
  isTunnelViewportFrame,
  isViewportBody,
  isViewportCursor,
  isMobileViewportSseEvent,
  MOBILE_VIEWPORT_SSE_EVENT,
  MOBILE_VIEWPORT_SSE_PATH_TEMPLATE,
  mobileViewportSsePath,
} from './tunnel-protocol.js';

// E2EE envelope + seal/open service (shared by Node PC + Hermes mobile)
export {
  E2EE_KEY_BYTES,
  E2EE_NONCE_BYTES,
  E2EE_ENVELOPE_VERSION,
  E2EE_ALG_XCHACHA20POLY1305,
  E2eeError,
  E2eeMalformedEnvelopeError,
  E2eeUnsupportedVersionError,
  E2eeUnsupportedAlgError,
  E2eeUnknownKeyError,
  E2eeAuthenticationError,
  E2eeInvalidKeyError,
  isE2eeEnvelope,
  type E2eeEnvelope,
  type E2eeEnvelopeVersion,
  type E2eeAlg,
  type E2eeRecipient,
  type E2eeLane,
  type E2eeDirection,
  type E2eeContext,
  type E2eeKeyProvider,
  type SealKey,
  type KeyLookup,
  type RandomBytes,
  buildAad,
  bytesToBase64,
  base64ToBytes,
  InvalidBase64Error,
  CryptoEnvelopeService,
  X25519_PRIVATE_KEY_BYTES,
  X25519_PUBLIC_KEY_BYTES,
  E2EE_KID_BYTES,
  deriveKid,
  generateX25519KeyPair,
  fromX25519PrivateKey,
  type E2eeKeyPair,
  E2EE_SHARED_KEY_BYTES,
  E2EE_HKDF_INFO,
  E2EE_HKDF_SALT,
  PAIRING_SECRET_BYTES,
  PAIRING_MAC_BYTES,
  deriveSharedKey,
  buildPairingTranscript,
  computePairingMac,
  verifyPairingMac,
  type PairingTranscriptInput,
  isE2eeVerified,
  reconcilePeerKey,
  markVerifiedViaSafetyNumber,
  type E2eeTrustStatus,
  type E2eeVerificationMethod,
  type E2eeAdoptionMethod,
  type E2eeTrustRecord,
  type IncomingPeerKey,
  E2EE_SAFETY_NUMBER_GROUPS,
  deriveSafetyNumber,
  E2EE_NEGOTIATION_VERSION,
  WORKSPACE_SUPPORT_VERSION,
  isWorkspaceSupportCapability,
  buildWorkspaceSupportCapability,
  isE2eeCapability,
  isCapable,
  negotiateE2ee,
  buildE2eeCapability,
  type E2eeCapability,
  type E2eeNegotiationMode,
  type E2eeNegotiationReason,
  type E2eeNegotiationResult,
  type WorkspaceSupportCapability,
} from './e2ee/index.js';

// Ed25519 device SIGNING key + RFC 7638 JWK thumbprint (device-bound refresh tokens).
// Shared verbatim by Node (identity service) + Hermes (mobile mirror).
export {
  ED25519_PRIVATE_KEY_BYTES,
  ED25519_PUBLIC_KEY_BYTES,
  ED25519_SIGNATURE_BYTES,
  DEVICE_KEY_KTY,
  DEVICE_KEY_CRV,
  fromEd25519PrivateKey,
  generateEd25519KeyPair,
  publicKeyToJwk,
  canonicalJwk,
  computeJwkThumbprint,
  signMessage,
  verifySignature,
  type Ed25519KeyPair,
  type Ed25519PublicJwk,
} from './device-key/index.js';

// Utilities
export {
  parseSemVer,
  isValidSemVer,
  compareSemVer,
  isGreaterThan,
  isLessThan,
  isEqual,
  sortVersions,
  getLatestVersion,
  formatSemVer,
  type SemVer,
} from './utils/index.js';
